# The size ratio of the image must be 5:1. The recommended scale is 1280x256 pixels.
# Useful Tools :
#   - Create your link with imgur: https://imgur.com (If you made it make sure you right-click and then open in new tab to get the right link)
#   - Make your image transparent with: https://onlinepngtools.com/create-transparent-png
server-banner-url: 'https://i.imgur.com/YdeR4J2.png'
